version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps)"
