apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .app }}
  labels:
    app: {{ .app }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .app }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          env:
            - name: GEOLITE_ASN_PATH
              value: "/usr/share/GeoLite2/GeoLite2-ASN.mmdb"
            - name: GEOLITE_CITY_PATH
              value: "/usr/share/GeoLite2/GeoLite2-City.mmdb"
      imagePullSecrets:
        - name: ghcrcred
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: {{ .domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .name }}
                port:
                  number: 80
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - {{ .domain }}
      secretName: {{ .name }}-ingress-cert
