name: binary-macos

on: pull_request

jobs:
  binary-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render template
        id: render
        uses: chuhlomin/render-template/binary@v1.11
        with:
          template: '.github/assets/test-template.md'
          vars: |
            name: world

      - name: Check result
        run: echo "${{ steps.render.outputs.result }}"
