name: main

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: us-central1-c
  DOCKER_IMAGE: ghcr.io/chuhlomin/ip
  DEPLOYMENT_NAME: ip

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Run tests
        env:
          GOPROXY: https://athens.chuhlomin.com
        run: go test -mod=readonly -v ./... -timeout=10m -coverprofile=coverage.txt

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ steps.docker_meta.outputs.tags }}

      - name: Deploy to GKE
        uses: chuhlomin/actions/deploy-gke@main
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          template_path: kube.yml
          vars: |
            image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            domain: ip.chuhlomin.com
            issuer: letsencrypt
            app: ip
            name: ip
          rollout_status_wait: deployment/${{ env.DEPLOYMENT_NAME }}
